# Project: Project2
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = 软件系统/main.o
LINKOBJ  = 软件系统/main.o
LIBS     = -L"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/lib" -L"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/include" -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/program_23/dev/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = homework_11.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = D:\program_23\dev\Dev-Cpp\devcpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

软件系统/main.o: 软件系统/main.cpp
	$(CPP) -c 软件系统/main.cpp -o 软件系统/main.o $(CXXFLAGS)
